// angular/lingua-angular/src/app/mainpage/courses/course/course.component.ts
import {Component, Input, OnInit} from '@angular/core';
import {Course} from "../../../../data/course";
import {MainpageService} from "../../mainpage.service";

@Component({
  selector: 'app-course',
  templateUrl: './course.component.html',
  styleUrls: ['./course.component.css']
})
export class CourseComponent implements OnInit {
  @Input() course: Course;

  constructor(private mainpageService: MainpageService) { }

  ngOnInit() {
  }

  getPrice(): string {
    return this.course.isFree ? "FREE" : "$" + this.course.price;
  }

  toggleActiveCourse(course: Course) {
    this.mainpageService.setActiveCourse(this.isActive() ? null : course);
  }

  isActive(): boolean {
    const activeCourse = this.mainpageService.getActiveCourse();
    return activeCourse ? activeCourse.id === this.course.id : false;
  }

}

<div (click)="toggleActiveCourse(course)"
     class="card"
     [class.course-panel]="!isActive()"
     [class.course-panel-selected]="isActive()">
  <p class="new-course-price-container"
     [class.free-price-container]="!course.isOpen && course.isFree"
     [class.price-container]="!course.isOpen && !course.isFree"
     [class.hidden-price-container]="course.isOpen">{{ getPrice() }}</p>
  <div class="course-info-container">
    <img class="rounded-circle circle-img" src="{{ course.img }}"/>
    <div class="course-info-text">
      <h6>{{ course.name }}</h6>
      <p>{{ course.shortDescription }}</p>
    </div>
  </div>
</div>

// react/lingua/src/components/mainpage/courses/Course.js
import React, { Component } from 'react';
import {Image, Panel} from "react-bootstrap";
import PropTypes from 'prop-types';

import "../../../styles.css";
import "./Course.css";

class Course extends Component {
    constructor(props) {
        super(props);

        this.setActiveCourse = this.setActiveCourse.bind(this);
    }

    setActiveCourse(courseId) {
        if (courseId === this.props.selectedCourseId) {
            this.props.deselectCourse();
        } else {
            this.props.selectCourse(courseId);
        }
    }

    render() {
        return(
            <Panel onClick={() => this.setActiveCourse(this.props.id)}
                   className={this.props.selectedCourseId === this.props.id ? "course-panel-selected" : "course-panel"}>
                {this.props.price
                    ? <p className={this.props.isFree ? "free-price-container" : "price-container"}>{this.props.price}</p>
                    : <p className="hidden-price-container">placeholder</p>
                }
                <div className="course-info-container">
                    <Image className="circle-img" src={this.props.img} circle />
                    <div className="course-info-text">
                        <h5>{this.props.name}</h5>
                        <p>{this.props.desc}</p>
                    </div>
                </div>
            </Panel>
        );
    }
}

Course.propTypes = {
    id: PropTypes.number.isRequired,
    name: PropTypes.string.isRequired,
    img: PropTypes.string.isRequired,
    desc: PropTypes.string.isRequired,
    isFree: PropTypes.bool,
    price: PropTypes.string,
    selectedCourseId: PropTypes.number,
    selectCourse: PropTypes.func.isRequired,
    deselectCourse: PropTypes.func.isRequired
};

export default Course;
