// angular/lingua-angular/src/app/mainpage/course-info/course-info-header/course-info-header.component.ts
import {Component, Input, OnInit} from '@angular/core';
import {Course} from "../../../../data/course";
import {ApiService} from "../../../api.service";

@Component({
  selector: 'app-course-info-header',
  templateUrl: './course-info-header.component.html',
  styleUrls: ['./course-info-header.component.css']
})
export class CourseInfoHeaderComponent implements OnInit {
  @Input() course: Course;

  constructor(private apiService: ApiService) { }

  ngOnInit() {
  }

  getPrice(): string {
    return this.course.isFree ? 'FREE' : '$' + this.course.price;
  }

  handleButtonClick() {
    if (!this.course.isOpen) {
      this.apiService.startNewCourse(this.course.id);
    }
  }

  getButtonText(): string {
    return this.course.isOpen ? 'Continue' : 'Start';
  }
}

<div class="course-header-container">
  <div class="course-header-info">
    <img class="img-circle circle-img" src="{{ course.img }}"/>
    <div class="course-header-info-text">
      <h5>{{ course.name }}</h5>
      <p class="selected-course-price-container"
         [class.free-price-container]="!course.isOpen && course.isFree"
         [class.price-container]="!course.isOpen && !course.isFree"
         [class.hidden-price-container]="course.isOpen">{{ getPrice() }}</p>
    </div>
  </div>
  <a routerLink="/courses/{{ course.id }}"
     class="flex__1">
    <button type="button"
            class="btn btn-primary"
            (click)="handleButtonClick()">{{ getButtonText() }}</button>
  </a>
</div>

// react/lingua/src/components/mainpage/courseinfo/CourseInfoHeader.js
import React, {Component} from "react";
import {Button, Image} from "react-bootstrap";
import PropTypes from 'prop-types';

import {startNewCourse} from "../../../utils/ApiService";
import {Link} from "react-router-dom";

import "../../shared/styles.css";
import "./CourseInfoHeader.css";

class CourseInfoHeader extends Component {
    constructor(props) {
        super(props);

        this.handleStartButtonClick = this.handleStartButtonClick.bind(this);
    }

    handleStartButtonClick(event) {
        startNewCourse(this.props.user, this.props.id);
    }

    render(){
        return(
            <div className="course-header-container">
                <div className="course-header-info">
                    <Image className="circle-img" src={this.props.img} circle />
                    <div className="course-header-info-text">
                        <h5>{this.props.name}</h5>
                        {!this.props.isOpen
                            ? <p className={this.props.isFree
                                ? "free-price-container selected-course-price-container"
                                : "price-container selected-course-price-container"}>
                                {this.props.price}
                            </p>
                            : <p className="hidden-price-container selected-course-price-container">placeholder</p>
                        }
                    </div>
                </div>
                <Link to={"/courses/" + this.props.id}
                      onClick={this.props.isOpen ? () => {} : this.handleStartButtonClick}
                      className="flex__1">
                    <Button bsStyle="primary">
                        {this.props.isOpen ? "Continue" : "Start"}
                    </Button>
                </Link>
            </div>
        );
    }
}

CourseInfoHeader.propTypes = {
    user: PropTypes.object,
    id: PropTypes.number.isRequired,
    name: PropTypes.string.isRequired,
    img: PropTypes.string.isRequired,
    isOpen: PropTypes.bool.isRequired,
    isFree: PropTypes.bool.isRequired,
    price: PropTypes.string.isRequired
};

export default CourseInfoHeader;
