// react/lingua-react/src/components/shared/Header.js
import React, { Component } from 'react';
import { Button, Navbar, Nav, NavItem, FormGroup, FormControl, Image } from 'react-bootstrap';
import PropTypes from 'prop-types';

import "./styles.css";
import "./Header.css";
import {Link} from "react-router-dom";
import {LinkContainer} from "react-router-bootstrap";

function NavLinks(props) {
    return (
        <Nav>
            <LinkContainer to="/courses">
                <NavItem className="nav-item">
                    Courses
                </NavItem>
            </LinkContainer>
            <LinkContainer to="/natives">
                <NavItem className="nav-item">
                    Talk with native
                </NavItem>
            </LinkContainer>
        </Nav>
    );
}

function NavSearch(props) {
    return (
        <Navbar.Collapse>
            <Navbar.Form pullRight>
                <FormGroup>
                    <FormControl type="text" placeholder="Search"/>
                </FormGroup>{' '}
                <Button type="submit">Submit</Button>
            </Navbar.Form>
        </Navbar.Collapse>
    );
}

class Header extends Component {
    render() {
        return (
            <div className="header-container">
                <Navbar className="margin__0 navbar-container">
                    <Navbar.Header>
                        <Navbar.Brand>
                            <a className="bold-text" href="/">Lingua</a>
                        </Navbar.Brand>
                    </Navbar.Header>
                    <NavLinks/>
                    <NavSearch/>
                </Navbar>
                <Link to="/settings" className="user-img-container">
                    <Image className="circle-img user-img" src={this.props.userAvatarSrc} circle />
                </Link>
            </div>
        );
    }
}

Header.propTypes = {
    userAvatarSrc: PropTypes.string.isRequired
} ;

export default Header;

// angular/lingua-angular/src/app/header/header.component.ts
import { Component, OnInit } from '@angular/core';
import {ApiService} from "../api.service";

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent implements OnInit {
  userAvatarSrc: string;

  constructor(private apiService: ApiService) { }

  ngOnInit() {
    this.getUserAvatar();
  }

  getUserAvatar() {
    this.apiService.getUserData()
      .subscribe(userData => {
        this.userAvatarSrc = userData.img;
      });
  }

}

<div class="header-container">
  <nav class="navbar navbar-expand-lg navbar-light bg-light margin__0 navbar-container rounded">
    <a class="navbar-brand" routerLink="/">Lingua</a>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" routerLink="/courses">Courses</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" routerLink="/natives">Talk with native</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn my-2 my-sm-0" type="submit">Submit</button>
    </form>
  </nav>
  <a routerLink="/settings" class="user-img-container">
    <img class="rounded-circle circle-img user-img" src="{{ userAvatarSrc }}"/>
  </a>
</div>
