// react/lingua/src/components/mainpage/filter/tabs/AdvancedTab.js
import React, {Component} from 'react';
import {Button, Checkbox, ControlLabel, FormControl, FormGroup} from "react-bootstrap";
import PropTypes from 'prop-types';

import './AdvanceTabs.css';

class AdvancedTab extends Component {
    constructor(props) {
        super(props);

        this.state = {
            keywords: this.props.advancedFilter.keywords ? this.props.advancedFilter.keywords : "",
            minPrice: this.props.advancedFilter.minPrice ? this.props.advancedFilter.minPrice : "",
            maxPrice: this.props.advancedFilter.maxPrice ? this.props.advancedFilter.maxPrice : "",
            freeOnly: this.props.advancedFilter.freeOnly ? this.props.advancedFilter.freeOnly : false
        };

        this.handleSubmit = this.handleSubmit.bind(this);
        this.handleFormChange = this.handleFormChange.bind(this);
    }

    handleSubmit(event) {
        this.props.setAdvancedFilter(this.state);
        event.preventDefault();
    }

    handleFormChange(event) {
        const target = event.target;
        const value = target.type === 'checkbox' ? target.checked : target.value;
        const name = target.name;

        this.setState({
            [name]: value
        });
    }

    render() {
        return(
            <form className="padding__10" onSubmit={this.handleSubmit}>
                <FormGroup controlId="keywordsFilterForm">
                    <ControlLabel>Keywords</ControlLabel>
                    <FormControl type="text"
                                 placeholder="Enter keywords"
                                 onChange={this.handleFormChange}
                                 name="keywords"
                                 value={this.state.keywords} />
                </FormGroup>
                <FormGroup controlId="priceFilterForm">
                    <ControlLabel>Price</ControlLabel>
                    <div className="inline-form-container">
                        <FormControl className="inline-form-member__2p5"
                                     type="text" placeholder="min"
                                     onChange={this.handleFormChange}
                                     name="minPrice"
                                     value={this.state.minPrice} />

                        <p className="inline-form-member__1">$ - </p>

                        <FormControl className="inline-form-member__2p5"
                                     type="text"
                                     placeholder="max"
                                     onChange={this.handleFormChange}
                                     name="maxPrice"
                                     value={this.state.maxPrice} />

                        <p className="inline-form-member__1">$</p>

                        <Checkbox checked={this.state.freeOnly}
                                  className="inline-form-member__6 checkbox-centered-content"
                                  onChange={this.handleFormChange}
                                  name="freeOnly">
                            Free only
                        </Checkbox>
                    </div>
                </FormGroup>
                <div className="flex__justify-right">
                    <Button type='submit'>Filter</Button>
                </div>
            </form>
        );
    }
}

AdvancedTab.propTypes = {
    advancedFilter: PropTypes.shape({
        keywords: PropTypes.string,
        minPrice: PropTypes.string,
        maxPrice: PropTypes.string,
        freeOnly: PropTypes.bool
    }).isRequired,
    setAdvancedFilter: PropTypes.func.isRequired
};

export default AdvancedTab;

// angular/lingua-angular/src/app/mainpage/filter/advanced-tab/advanced-tab.component.ts
import { Component, OnInit } from '@angular/core';
import {MainpageService} from "../../mainpage.service";

@Component({
  selector: 'app-advanced-tab',
  templateUrl: './advanced-tab.component.html',
  styleUrls: ['./advanced-tab.component.css']
})
export class AdvancedTabComponent implements OnInit {

  constructor(private mainpageService: MainpageService) { }

  ngOnInit() {
  }

  handleFilter(keywords: string, minPrice: string, maxPrice: string, freeOnly: boolean) {
    this.mainpageService.setAdvancedFilter(keywords, minPrice, maxPrice, freeOnly);
  }

  getKeywordsValue(): string {
    const advancedFilter = this.mainpageService.getAdvancedFilter();
    return (advancedFilter && advancedFilter.keywords) ? advancedFilter.keywords : ""
  }

  getMinPriceValue(): string {
    const advancedFilter = this.mainpageService.getAdvancedFilter();
    return (advancedFilter && advancedFilter.minPrice && advancedFilter.minPrice !== "-1") ? advancedFilter.minPrice : ""
  }

  getMaxPriceValue(): string {
    const advancedFilter = this.mainpageService.getAdvancedFilter();
    return (advancedFilter && advancedFilter.maxPrice && advancedFilter.maxPrice !== "-1") ? advancedFilter.maxPrice : ""
  }

  getFreeOnlyValue(): boolean {
    const advancedFilter = this.mainpageService.getAdvancedFilter();
    return (advancedFilter && advancedFilter.freeOnly) ? advancedFilter.freeOnly : false;
  }

}

<form class="padding__20">
  <div class="form-row">
    <div class="form-group width__100pc">
      <label>Keywords</label>
      <input #keywords
             type="text"
             class="form-control"
             id="keywords"
             value="{{ getKeywordsValue() }}"
             placeholder="Enter keywords">
    </div>
  </div>
  <div class="form-row">
    <div class="form-group">
      <label>Price</label>
      <div class="inline-form-container">
        <input #minPrice
               type="text"
               class="form-control inline-form-member__2p5 width__100pc"
               id="min-price"
               value="{{ getMinPriceValue() }}"
               placeholder="min">
        <p class="inline-form-member__1">$ - </p>
        <input #maxPrice
               type="text"
               class="form-control inline-form-member__2p5"
               id="max-price"
               value="{{ getMaxPriceValue() }}"
               placeholder="max">
        <p class="inline-form-member__1">$</p>
        <div class="form-check inline-form-member__6 checkbox-centered-content">
          <input #freeOnly
                 class="form-check-input"
                 type="checkbox"
                 id="freeOnly"
                 [checked]="getFreeOnlyValue()">
          <label class="form-check-label" for="freeOnly">
            Free only
          </label>
        </div>
      </div>
    </div>
  </div>
  <div class="form-row flex__justify-right">
    <button (click)="handleFilter(keywords.value, minPrice.value, maxPrice.value, freeOnly.checked); false" class="btn btn-light">Filter</button>
  </div>
</form>
