// react/lingua/src/components/mainpage/filter/Filter.js
import React, {Component} from 'react'
import {Panel, Tab, Tabs} from "react-bootstrap";

import LanguageTab from "../../../containers/mainpage/filter/tabs/LanguageTabContainer";
import AdvancedTab from "./tabs/AdvancedTab";

import "../../../styles.css";

class Filter extends Component {
    render() {
        return (
            <div className="height__100pc flex-col">
                <h2 className="center-text">Filter</h2>
                <Panel className="flex__1 overflow-y__auto">
                    <Panel.Body className="padding__0">
                        <Tabs defaultActiveKey={0} id="filter-tabs">
                            <Tab eventKey={0} title="Languages">
                                <LanguageTab/>
                            </Tab>
                            <Tab eventKey={1} title="Advanced">
                                <AdvancedTab/>
                            </Tab>
                        </Tabs>
                    </Panel.Body>
                </Panel>
            </div>
        );
    }
}

export default Filter;

// angular/lingua-angular/src/app/mainpage/filter/filter.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-filter',
  templateUrl: './filter.component.html',
  styleUrls: ['./filter.component.css']
})
export class FilterComponent implements OnInit {
  readonly LANGUAGE_TAB = "languages";
  readonly ADVANCED_TAB = "advanced";

  selectedTab = this.LANGUAGE_TAB;

  constructor() { }

  ngOnInit() {
  }

  setSelectedTab(selectedTab: string) {
    this.selectedTab = selectedTab;
  }

}

<div class="height__100pc flex-col">
  <h3 class="center-text">Filter</h3>
  <div class="card flex__1 overflow-y__auto">
    <div class="card-body padding__0">
      <ul class="nav nav-tabs">
        <li class="nav-item">
          <a class="nav-link"
             href="#"
             (click)="setSelectedTab(LANGUAGE_TAB); false"
             [class.active]="selectedTab === LANGUAGE_TAB">Languages</a>
        </li>
        <li class="nav-item">
          <a class="nav-link"
             href="#"
             (click)="setSelectedTab(ADVANCED_TAB); false"
             [class.active]="selectedTab === ADVANCED_TAB">Advanced</a>
        </li>
      </ul>
    </div>
  </div>
</div>
